# Generated by Django 4.2.5 on 2024-02-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_loanamout_martialstatus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loanamout",
            name="day",
        ),
        migrations.RemoveField(
            model_name="loanamout",
            name="month",
        ),
        migrations.RemoveField(
            model_name="loanamout",
            name="year",
        ),
        migrations.AddField(
            model_name="loanamout",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
