# Generated by Django 4.2.5 on 2024-02-22 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_loanamout_day_remove_loanamout_month_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanamout",
            name="date",
            field=models.DateField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
    ]
